# Generated by Django 3.1.7 on 2021-08-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210810_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/home/damilola/python/sca/media/images/no_image.png', upload_to='images/courses/'),
        ),
    ]
