# Generated by Django 3.1.7 on 2021-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210810_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='images/courses/'),
        ),
    ]
